<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Title>远程助手</Title>
    <AssemblyTitle>远程助手</AssemblyTitle>
    <Product>远程助手</Product>
    <AssemblyName>RemoteAssistant</AssemblyName>
    <RootNamespace>RemoteAssistant</RootNamespace>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="work\**\*.cs" />
  </ItemGroup>
</Project>
